workingDirectory <- getwd()
codeFolder <- paste(projectFolder, "Code", sep="/")

# Imputation code provided to me
setwd(paste(codeFolder, "Impute", sep="/"))
source("checkData.R")
source("ginv.R")
source("llsImpute.R")

# Code I wrote for the tests
setwd(paste(codeFolder, "Tests", sep="/"))
source("affinityMatrix.R")
source("calAcc.R")
# source("dominateset.R")
source("evaluateClustering.R")
source("evaluateClusteringCensor.R")
source("evaluateClusteringInt.R")
source("evaluateClusteringLab.R")
source("evaluateImputation.R")
source("evaluateSimilarity.R")
source("evaluateSimilarityInt.R")
source("evaluateSimilarityLab.R")
source("evaluateSimilarityCustom.R")
source("evaluateSurvival.R")
source("evaluateSurvivalCensor.R")
source("generateIncompleteIntersection.R")
source("generateIncompleteIntersectionPercent.R")
source("generateIncompleteIntersectionCombat.R")
source("hierarchicalClustering.R")
source("hierarchicalClusteringType.R")
source("iClusterClustering.R")
source("iClusterClusteringType.R")
source("imputationErrors.R")
source("knnImputation.R")
source("llsImputation.R")
# Note: lsaImputation depends on previously initialized variables:
# -imputedFile, incompleteFile, projectFolder, jvmGBLimit
source("lsaImputation.R")
source("medianSimilarity.R")
source("randomImputation.R")
source("regressionSimilarity.R")
source("sampleIntersection.R")
source("sampleUnion.R")
source("selfSimilarity.R")
source("SNFClustering.R")
source("SNFClusteringType.R")
source("splitConcatenatedData.R")
source("standardNormalization.R")
source("writeResults.R")

setwd(workingDirectory)
